project_id = "guivxjcnxgkhpfhsjqbl"

[functions.train-lora]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.sync-lora-status]
verify_jwt = true

[functions.support-chat]
verify_jwt = false
