/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibeRouteImport } from './routes/vibe'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'

const VibeRoute = VibeRouteImport.update({
  id: '/vibe',
  path: '/vibe',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/presets': typeof PresetsRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/vibe': typeof VibeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/presets': typeof PresetsRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/vibe': typeof VibeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/presets': typeof PresetsRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/vibe': typeof VibeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/auth'
    | '/library'
    | '/presets'
    | '/queue'
    | '/settings'
    | '/studio'
    | '/vibe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/auth'
    | '/library'
    | '/presets'
    | '/queue'
    | '/settings'
    | '/studio'
    | '/vibe'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/auth'
    | '/library'
    | '/presets'
    | '/queue'
    | '/settings'
    | '/studio'
    | '/vibe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  PresetsRoute: typeof PresetsRoute
  QueueRoute: typeof QueueRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  VibeRoute: typeof VibeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibe': {
      id: '/vibe'
      path: '/vibe'
      fullPath: '/vibe'
      preLoaderRoute: typeof VibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  PresetsRoute: PresetsRoute,
  QueueRoute: QueueRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  VibeRoute: VibeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
