/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibeRouteImport } from './routes/vibe'
import { Route as TrainRouteImport } from './routes/train'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as LorasRouteImport } from './routes/loras'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack/webhook'
import { Route as ApiPublicHooksReplicateTrainingRouteImport } from './routes/api/public/hooks/replicate-training'
import { Route as ApiPublicHooksProcessQueueRouteImport } from './routes/api/public/hooks/process-queue'

const VibeRoute = VibeRouteImport.update({
  id: '/vibe',
  path: '/vibe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const LorasRoute = LorasRouteImport.update({
  id: '/loras',
  path: '/loras',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReplicateTrainingRoute =
  ApiPublicHooksReplicateTrainingRouteImport.update({
    id: '/api/public/hooks/replicate-training',
    path: '/api/public/hooks/replicate-training',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessQueueRoute =
  ApiPublicHooksProcessQueueRouteImport.update({
    id: '/api/public/hooks/process-queue',
    path: '/api/public/hooks/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/library': typeof LibraryRoute
  '/loras': typeof LorasRoute
  '/presets': typeof PresetsRoute
  '/pricing': typeof PricingRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/train': typeof TrainRoute
  '/vibe': typeof VibeRoute
  '/api/public/hooks/process-queue': typeof ApiPublicHooksProcessQueueRoute
  '/api/public/hooks/replicate-training': typeof ApiPublicHooksReplicateTrainingRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/library': typeof LibraryRoute
  '/loras': typeof LorasRoute
  '/presets': typeof PresetsRoute
  '/pricing': typeof PricingRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/train': typeof TrainRoute
  '/vibe': typeof VibeRoute
  '/api/public/hooks/process-queue': typeof ApiPublicHooksProcessQueueRoute
  '/api/public/hooks/replicate-training': typeof ApiPublicHooksReplicateTrainingRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/library': typeof LibraryRoute
  '/loras': typeof LorasRoute
  '/presets': typeof PresetsRoute
  '/pricing': typeof PricingRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/train': typeof TrainRoute
  '/vibe': typeof VibeRoute
  '/api/public/hooks/process-queue': typeof ApiPublicHooksProcessQueueRoute
  '/api/public/hooks/replicate-training': typeof ApiPublicHooksReplicateTrainingRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assets'
    | '/auth'
    | '/contact'
    | '/library'
    | '/loras'
    | '/presets'
    | '/pricing'
    | '/queue'
    | '/settings'
    | '/studio'
    | '/train'
    | '/vibe'
    | '/api/public/hooks/process-queue'
    | '/api/public/hooks/replicate-training'
    | '/api/public/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assets'
    | '/auth'
    | '/contact'
    | '/library'
    | '/loras'
    | '/presets'
    | '/pricing'
    | '/queue'
    | '/settings'
    | '/studio'
    | '/train'
    | '/vibe'
    | '/api/public/hooks/process-queue'
    | '/api/public/hooks/replicate-training'
    | '/api/public/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assets'
    | '/auth'
    | '/contact'
    | '/library'
    | '/loras'
    | '/presets'
    | '/pricing'
    | '/queue'
    | '/settings'
    | '/studio'
    | '/train'
    | '/vibe'
    | '/api/public/hooks/process-queue'
    | '/api/public/hooks/replicate-training'
    | '/api/public/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LibraryRoute: typeof LibraryRoute
  LorasRoute: typeof LorasRoute
  PresetsRoute: typeof PresetsRoute
  PricingRoute: typeof PricingRoute
  QueueRoute: typeof QueueRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  TrainRoute: typeof TrainRoute
  VibeRoute: typeof VibeRoute
  ApiPublicHooksProcessQueueRoute: typeof ApiPublicHooksProcessQueueRoute
  ApiPublicHooksReplicateTrainingRoute: typeof ApiPublicHooksReplicateTrainingRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibe': {
      id: '/vibe'
      path: '/vibe'
      fullPath: '/vibe'
      preLoaderRoute: typeof VibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loras': {
      id: '/loras'
      path: '/loras'
      fullPath: '/loras'
      preLoaderRoute: typeof LorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/replicate-training': {
      id: '/api/public/hooks/replicate-training'
      path: '/api/public/hooks/replicate-training'
      fullPath: '/api/public/hooks/replicate-training'
      preLoaderRoute: typeof ApiPublicHooksReplicateTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-queue': {
      id: '/api/public/hooks/process-queue'
      path: '/api/public/hooks/process-queue'
      fullPath: '/api/public/hooks/process-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LibraryRoute: LibraryRoute,
  LorasRoute: LorasRoute,
  PresetsRoute: PresetsRoute,
  PricingRoute: PricingRoute,
  QueueRoute: QueueRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  TrainRoute: TrainRoute,
  VibeRoute: VibeRoute,
  ApiPublicHooksProcessQueueRoute: ApiPublicHooksProcessQueueRoute,
  ApiPublicHooksReplicateTrainingRoute: ApiPublicHooksReplicateTrainingRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
